# Generated by Django 5.2.11 on 2026-02-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoAnalysis',
        ),
    ]
