# Generated by Django 4.2.27 on 2026-02-06 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('public_url', models.URLField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
