# Generated by Django 4.2.27 on 2026-02-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantdocument',
            name='public_url',
        ),
    ]
