# Generated by Django 5.2.11 on 2026-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_documents', '0002_remove_consultantdocument_public_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdocument',
            name='gemini_raw_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultantdocument',
            name='verification_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
