# Generated by Django 4.2.27 on 2026-02-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='usersession',
            name='question_set',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='selected_domains',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usersession',
            name='video_question_set',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='question_identifier',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.batch'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.testtype'),
        ),
    ]
