# Generated by Django 4.2.27 on 2026-02-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_videoresponse_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
