# Generated by Django 4.2.27 on 2026-02-16 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0003_remove_question_batch_remove_usersession_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='candidate',
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
