# Generated by Django 5.2.11 on 2026-02-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_remove_usersession_candidate_usersession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresponse',
            name='ai_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='ai_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
