# Generated by Django 5.2.11 on 2026-02-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_videoresponse_ai_feedback_videoresponse_ai_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_violation', models.BooleanField(default=False)),
                ('violation_reason', models.TextField(blank=True, null=True)),
                ('face_count', models.IntegerField(default=0)),
                ('match_score', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_snapshots', to='assessment.usersession')),
            ],
        ),
    ]
