# Generated by Django 5.2.11 on 2026-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_proctoringsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='audio_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='gaze_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='label_detection_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='mouth_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='pose_pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='pose_roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='pose_yaw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
