# Generated by Django 5.2.11 on 2026-03-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_proctoringsnapshot_telemetry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='rule_outcomes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
