# Generated by Django 5.2.11 on 2026-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_proctoringsnapshot_rule_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='violation_counters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
