# Generated by Django 4.2.27 on 2026-02-06 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultant Expertise',
                'verbose_name_plural': 'Consultant Expertises',
                'db_table': 'consultant_expertise',
                'unique_together': {('user', 'domain', 'service')},
            },
        ),
    ]
