# Generated by Django 4.2.27 on 2026-02-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_consultantexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('LLP', 'LLP'), ('Firm', 'Firm'), ('Partnership', 'Partnership'), ('Company', 'Company')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
