# Generated by Django 4.2.27 on 2026-02-13 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_address_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Qualification', 'Qualification Degree'), ('Certificate', 'Certificate')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='consultant_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultant Document',
                'verbose_name_plural': 'Consultant Documents',
                'db_table': 'consultant_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
