# Generated by Django 4.2.27 on 2026-02-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_consultantdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultantExpertise',
        ),
    ]
