# Generated by Django 4.2.27 on 2026-02-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_consultantexpertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.AlterField(
            model_name='user',
            name='practice_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual')], max_length=50, null=True),
        ),
    ]
