# Generated by Django 4.2.27 on 2026-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_identitydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantdocument',
            name='document_type',
            field=models.CharField(choices=[('Qualification', 'Qualification Degree'), ('Certificate', 'Certificate'), ('bachelors_degree', "Bachelor's Degree"), ('masters_degree', "Master's Degree"), ('certificate', 'Certificate (Additional)')], max_length=50),
        ),
    ]
