# Generated by Django 4.2.27 on 2026-02-17 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_consultantdocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultant Credential',
                'verbose_name_plural': 'Consultant Credentials',
                'db_table': 'consultant_credentials',
            },
        ),
    ]
