# Generated by Django 5.2.11 on 2026-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_consultantcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='document_type',
            field=models.CharField(blank=True, help_text='Type of document identified by Gemini (e.g., Aadhaar, PAN)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='gemini_raw_response',
            field=models.TextField(blank=True, help_text='Raw JSON response from Gemini', null=True),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='verification_status',
            field=models.CharField(blank=True, help_text='Verification status from Gemini (e.g., Verified, Invalid)', max_length=50, null=True),
        ),
    ]
