# Generated by Django 5.2.11 on 2026-02-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_identitydocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_declaration',
            field=models.BooleanField(default=False),
        ),
    ]
