# Generated by Django 6.0.3 on 2026-03-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_has_accepted_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdocument',
            name='gemini_raw_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultantdocument',
            name='verification_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultantdocument',
            name='document_type',
            field=models.CharField(choices=[('Qualification', 'Qualification Degree'), ('Certificate', 'Certificate'), ('bachelors_degree', "Bachelor's Degree"), ('masters_degree', "Master's Degree"), ('certificate', 'Certificate (Additional)'), ('experience_letter', 'Experience Letter')], max_length=50),
        ),
    ]
