# Generated by Django 4.2.27 on 2026-02-09 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image_path', models.CharField(max_length=255)),
                ('live_image_path', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_match', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'face_verifications',
                'ordering': ['-verified_at'],
            },
        ),
    ]
