# Generated by Django 4.2.27 on 2026-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverification',
            name='live_image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
